FROM debian:latest

RUN apt-get update && apt-get install python3-pip -y && pip3 install requests==2.22.0

ADD modeler.py /model/modeler.py

ADD requirements.txt /

RUN pip3 install requirements.txt

WORKDIR /model

CMD python3 modeler.py
